server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://cwadmin:cwadmin@localhost:8081/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: yuntu-mobile